# Generated by Django 5.1.3 on 2024-11-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="summary",
            field=models.TextField(default="this is cool!"),
        ),
    ]
