# Generated by Django 5.1.3 on 2024-11-23 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_products_summary"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Products",
            new_name="Product",
        ),
    ]
