# Generated by Django 5.1.3 on 2024-11-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_rename_products_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(default="Description of Product "),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.TextField(default="19.99"),
        ),
        migrations.AddField(
            model_name="product",
            name="title",
            field=models.CharField(default="Product", max_length=255),
        ),
    ]
